name: pfall
description: "A CLI tool to run `flutter pub get` in all subdirectories containing a pubspec.yaml."
version: 1.0.6
repository: https://github.com/loveoverflowcom/pfall
homepage: https://github.com/loveoverflowcom/pfall

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  pfall: pfall
